ktor:
    deployment:
        port: "$PORT:8080"
    application:
        modules:
            - com.raylabs.laundryhub.backend.ApplicationKt.module

storage:
    jdbcUrl: "jdbc:h2:mem:laundryhub;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
